eureka:
  client:
    service-url:
      dafaultZone: http:localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
server:
  port: 8763
spring:
  application:
    name: service-first